--require("__thelian-lib__/data/item-groups.lua")
  data:extend({
    {
      type = "item",
      name = "le-boiler",
      icon = "__base__/graphics/icons/boiler.png",
      icon_size = 64,
      icon_mipmaps = 4,
      subgroup = "ti-steam-power",
      order = "a[ti-steam-power]-a[le-boiler]",
      place_result = "le-boiler",
      stack_size = 50,
    },
    {
      type = "item",
      name = "me-boiler",
      icon = "__base__/graphics/icons/boiler.png",
      icon_size = 64,
      icon_mipmaps = 4,
      subgroup = "ti-steam-power",
      order = "a[ti-steam-power]-b[me-boiler]",
      place_result = "me-boiler",
      stack_size = 50,
    },
    {
      type = "item",
      name = "he-boiler",
      icon = "__base__/graphics/icons/boiler.png",
      icon_size = 64,
      icon_mipmaps = 4,
      subgroup = "ti-steam-power",
      order = "a[ti-steam-power]-c[he-boiler]",
      place_result = "he-boiler",
      stack_size = 50,
    },
    {
      type = "item",
      name = "se-boiler",
      icon = "__base__/graphics/icons/boiler.png",
      icon_size = 64,
      icon_mipmaps = 4,
      subgroup = "ti-steam-power",
      order = "a[ti-steam-power]-d[se-boiler]",
      place_result = "se-boiler",
      stack_size = 50,
    },
    -- Fluid Boilers
    {
      type = "item",
      name = "s-gas-boiler",
      icon = "__base__/graphics/icons/boiler.png",
      icon_size = 64,
      icon_mipmaps = 4,
      subgroup = "ti-steam-power",
      order = "a[ti-steam-power]-a[s-gas-boiler]",
      place_result = "s-gas-boiler",
      stack_size = 50,
    },
    {
      type = "item",
      name = "he-gas-boiler",
      icon = "__base__/graphics/icons/boiler.png",
      icon_size = 64,
      icon_mipmaps = 4,
      subgroup = "ti-steam-power",
      order = "a[ti-steam-power]-b[he-gas-boiler]",
      place_result = "he-gas-boiler",
      stack_size = 50,
    },
  })
