--require("__thelian-lib__/data/item-groups.lua")

if settings.startup["ti-transmission-overhaul"].value == true then
    data:extend({
        {
            type = "item",
            name = "small-transmission-pole",
            icon = "__base__/graphics/icons/medium-electric-pole.png",
            icon_size = 64,
            icon_mipmaps = 4,
            subgroup = "ti-transmission",
            order = "b[ti-transmission]-a[small-transmission-pole]",
            place_result = "small-transmission-pole",
            stack_size = 100,
          },
          {
            type = "item",
            name = "medium-transmission-pole",
            icon = "__base__/graphics/icons/medium-electric-pole.png",
            icon_size = 64,
            icon_mipmaps = 4,
            subgroup = "ti-transmission",
            order = "b[ti-transmission]-a[medium-transmission-pole]",
            place_result = "medium-transmission-pole",
            stack_size = 100,
          },
          {
            type = "item",
            name = "long-transmission-pole",
            icon = "__base__/graphics/icons/big-electric-pole.png",
            icon_size = 64,
            icon_mipmaps = 4,
            subgroup = "ti-transmission",
            order = "b[ti-transmission]-a[long-transmission-pole]",
            place_result = "long-transmission-pole",
            stack_size = 100,
          },
          {
            type = "item",
            name = "industrial-transmission-pole",
            icon = "__base__/graphics/icons/big-electric-pole.png",
            icon_size = 64,
            icon_mipmaps = 4,
            subgroup = "ti-transmission",
            order = "b[ti-transmission]-a[industrial-transmission-pole]",
            place_result = "industrial-transmission-pole",
            stack_size = 100,
          },
          {
            type = "item",
            name = "small-area-transformer",
            icon = "__base__/graphics/icons/substation.png",
            icon_size = 64,
            icon_mipmaps = 4,
            subgroup = "ti-transmission",
            order = "b[ti-transmission]-a[small-area-transformer]",
            place_result = "small-area-transformer",
            stack_size = 100,
          },
          {
            type = "item",
            name = "medium-area-transformer",
            icon = "__base__/graphics/icons/substation.png",
            icon_size = 64,
            icon_mipmaps = 4,
            subgroup = "ti-transmission",
            order = "b[ti-transmission]-a[medium-area-transformer]",
            place_result = "medium-area-transformer",
            stack_size = 100,
          },
          {
            type = "item",
            name = "large-area-transformer",
            icon = "__base__/graphics/icons/substation.png",
            icon_size = 64,
            icon_mipmaps = 4,
            subgroup = "ti-transmission",
            order = "b[ti-transmission]-a[large-area-transformer]",
            place_result = "large-area-transformer",
            stack_size = 100,
          },
          {
            type = "item",
            name = "industrial-transformer",
            icon = "__base__/graphics/icons/substation.png",
            icon_size = 64,
            icon_mipmaps = 4,
            subgroup = "ti-transmission",
            order = "b[ti-transmission]-a[industrial-transformer]",
            place_result = "industrial-transformer",
            stack_size = 100,
          },
    })
end