data:extend({
    {
        type = "item",
        name = "le-steam-engine",
        icon = "__base__/graphics/icons/steam-engine.png",
        icon_size = 64,
        icon_mipmaps = 4,
        subgroup = "ti-steam-power",
        order = "b[ti-steam-power]-a[le-steam-engine]",
        place_result = "le-steam-engine",
        stack_size = 10,
      },
      {
        type = "item",
        name = "me-steam-engine",
        icon = "__base__/graphics/icons/steam-engine.png",
        icon_size = 64,
        icon_mipmaps = 4,
        subgroup = "ti-steam-power",
        order = "b[ti-steam-power]-b[me-steam-engine]",
        place_result = "me-steam-engine",
        stack_size = 10,
      },
      {
        type = "item",
        name = "se-turbine",
        icon = "__base__/graphics/icons/steam-turbine.png",
        icon_size = 64,
        icon_mipmaps = 4,
        subgroup = "ti-steam-power",
        order = "b[ti-steam-power]-c[se-turbine]",
        place_result = "se-turbine",
        stack_size = 10,
      },
      {
        type = "item",
        name = "he-turbine",
        icon = "__base__/graphics/icons/steam-turbine.png",
        icon_size = 64,
        icon_mipmaps = 4,
        subgroup = "ti-steam-power",
        order = "b[ti-steam-power]-d[he-turbine]",
        place_result = "he-turbine",
        stack_size = 10,
      },
})